version: 0.2

phases:

  install:
    commands:
      - echo nothing to install here...go ahead please

  pre_build:
    commands:
      - echo -e "export const api_id=$API_ID; \nexport const env=$ENV" > config.js
      - echo config file setup is done...


  build:
    commands:
      - aws s3 sync . s3://proj-alpha-dev/

  post_build:
    commands:
