version: 0.2

phases:

  install:
    commands:
      - echo nothing to install here...go ahead please

  pre_build:
    commands:
      - echo  "export const api_id='$API_ID'; \nexport const env='$ENV'" > config.js
      - echo config file setup is done...


  build:
    commands:
      - aws s3 sync . $DESTINATION_BUCKET --delete --exclude ".git/*" --exclude "config.js"
      - aws s3 cp ./config.js $DESTINATION_BUCKET
      - echo syncing done with the s3.....

  post_build:
    commands:
      - echo invalidating caches of the cdn if production deployment happend
      - |
      if ["$ENV" = "prod"]; then

        AWS_MAX_ATTEMPTS=10;
        aws cloudfront create-invalidation --distribution-id E22BE96CQLD3I8 --paths "/*";
      fi
      - echo all is done at `date`
