version: 0.2

phases:

  install:
    commands:
      - echo nothing to install here...go ahead please

  pre_build:
    commands:
      - echo -e "export const api_id=$API_ID; \nexport const env=$ENV" > config.js
      - echo config file setup is done...


  build:
    commands:
      - aws s3 sync . s3://proj-alpha-dev/ --delete --exclude ".git/*" --exclude "config.js"
      - aws s3 cp ./config.js s3://proj-alpha-dev/
      - echo syncing done with the s3.....

  post_build:
    commands:
      - echo all is done at `date`
